In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import json

# Read CSV file and form DataFrame

In [ ]:
csv_data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Class1/district_level_service_msme.csv")

In [ ]:
csv_data

,STATE_NAME,Lg_Dist_Code,DISTRICT_NAME,MICRO,SMALL,MEDIUM,Total,Last_Updated
0,ANDHRA PRADESH,502,ANANTHAPUR,7797,238,10,8045,2022-01-11
1,ANDHRA PRADESH,503,CHITOOR,9623,351,19,9993,2022-01-11
2,ANDHRA PRADESH,505,EAST GODAVARI,12347,615,49,13011,2022-01-11
3,ANDHRA PRADESH,506,GUNTUR,11386,630,53,12069,2022-01-11
4,ANDHRA PRADESH,510,KRISHNA,15189,1007,79,16275,2022-01-11
...,...,...,...,...,...,...,...,...
733,LAKSHADWEEP,553,LAKSHADWEEP DISTRICT,114,0,0,114,2022-01-11
734,PUDUCHERRY,598,KARAIKAL,989,47,1,1037,2022-01-11
735,PUDUCHERRY,599,MAHE,71,11,0,82,2022-01-11
736,PUDUCHERRY,600,PONDICHERRY,5577,202,21,5800,2022-01-11
737,PUDUCHERRY,601,YANAM,65,6,0,71,2022-01-11

In [ ]:
df1 = pd.DataFrame(csv_data)
df1

,STATE_NAME,Lg_Dist_Code,DISTRICT_NAME,MICRO,SMALL,MEDIUM,Total,Last_Updated
0,ANDHRA PRADESH,502,ANANTHAPUR,7797,238,10,8045,2022-01-11
1,ANDHRA PRADESH,503,CHITOOR,9623,351,19,9993,2022-01-11
2,ANDHRA PRADESH,505,EAST GODAVARI,12347,615,49,13011,2022-01-11
3,ANDHRA PRADESH,506,GUNTUR,11386,630,53,12069,2022-01-11
4,ANDHRA PRADESH,510,KRISHNA,15189,1007,79,16275,2022-01-11
...,...,...,...,...,...,...,...,...
733,LAKSHADWEEP,553,LAKSHADWEEP DISTRICT,114,0,0,114,2022-01-11
734,PUDUCHERRY,598,KARAIKAL,989,47,1,1037,2022-01-11
735,PUDUCHERRY,599,MAHE,71,11,0,82,2022-01-11
736,PUDUCHERRY,600,PONDICHERRY,5577,202,21,5800,2022-01-11
737,PUDUCHERRY,601,YANAM,65,6,0,71,2022-01-11

#Reading json and forming dataFrame

In [ ]:
#from json
filepath="/content/drive/MyDrive/Colab Notebooks/Class1/district_level_manufacturing_msme.json"
f = open(filepath)
data=json.load(f)

# # Create data frame
df=pd.DataFrame(data["data"])

# # Assign  names to columns
clmns=[dic["label"] for dic in data["fields"]]
df2=pd.DataFrame(data["data"],columns=clmns)
print(df2)

         STATE_NAME Lg_Dist_Code         DISTRICT_NAME  MICRO SMALL MEDIUM  \
0    ANDHRA PRADESH          502            ANANTHAPUR  11370   483     33
1    ANDHRA PRADESH          503               CHITOOR  13037   592     51
2    ANDHRA PRADESH          505         EAST GODAVARI  16711  1044    123
3    ANDHRA PRADESH          506                GUNTUR  15955  1678    169
4    ANDHRA PRADESH          510               KRISHNA  20460  1673    165
..              ...          ...                   ...    ...   ...    ...
732          LADAKH            9            LEH LADAKH   1493    35      0
733     LAKSHADWEEP          553  LAKSHADWEEP DISTRICT    150     0      0
734      PUDUCHERRY          598              KARAIKAL   1248    56      2
735      PUDUCHERRY          599                  MAHE     95    17      0
736      PUDUCHERRY          600           PONDICHERRY   7698   413     50

     Total Last_Updated
0    11886   2022-01-11
1    13680   2022-01-11
2    17878   2022-01-11
3    17802   2022-01-11
4    22298   2022-01-11
..     ...          ...
732   1528   2022-01-11
733    150   2022-01-11
734   1306   2022-01-11
735    112   2022-01-11
736   8161   2022-01-11

[737 rows x 8 columns]

In [ ]:
print(df1.columns)
print(df2.columns)

Index(['STATE_NAME', 'Lg_Dist_Code', 'DISTRICT_NAME', 'MICRO', 'SMALL',
       'MEDIUM', 'Total', 'Last_Updated'],
      dtype='object')
Index(['STATE_NAME', 'Lg_Dist_Code', 'DISTRICT_NAME', 'MICRO', 'SMALL',
       'MEDIUM', 'Total', 'Last_Updated'],
      dtype='object')

In [ ]:
df2["SMALL"] = pd.to_numeric(df2["SMALL"])
small_msme = df2.groupby("STATE_NAME")["SMALL"].sum()
small_msme

STATE_NAME
ANDAMAN AND NICOBAR ISLANDS      140
ANDHRA PRADESH                 10599
ARUNACHAL PRADESH                 99
ASSAM                           3345
BIHAR                           5226
CHANDIGARH                      1007
CHHATTISGARH                    4580
DADAR AND NAGAR HAVELI           419
DAMAN AND DIU                    295
DELHI                          19400
GOA                              713
GUJARAT                        38098
HARYANA                        16387
HIMACHAL PRADESH                1559
JAMMU AND KASHMIR               1854
JHARKHAND                       3492
KARNATAKA                      18996
KERALA                          8856
LADAKH                            49
LAKSHADWEEP                        0
MADHYA PRADESH                 12190
MAHARASHTRA                    49991
MANIPUR                          247
MEGHALAYA                        147
MIZORAM                           74
NAGALAND                          53
ODISHA                          5412
PUDUCHERRY                       486
PUNJAB                         12334
RAJASTHAN                      19456
SIKKIM                            56
TAMIL NADU                     30634
TELANGANA                      12540
TRIPURA                          252
UTTAR PRADESH                  21530
UTTARAKHAND                     2618
WEST BENGAL                    14088
Name: SMALL, dtype: int64

In [ ]:
pivot_table_result = df1.pivot_table(values=['SMALL', 'MICRO', 'MEDIUM'],
                                    index='STATE_NAME',
                                    aggfunc='sum')

pivot_table_result

                             MEDIUM   MICRO  SMALL
STATE_NAME
ANDAMAN AND NICOBAR ISLANDS       6    2884    111
ANDHRA PRADESH                  422  115320   5799
ARUNACHAL PRADESH                 6    1201     53
ASSAM                           200   41051   2182
BIHAR                           245  167835   3908
CHANDIGARH                       76    9010    687
CHHATTISGARH                    257   58905   2726
DADAR AND NAGAR HAVELI            3    2511     98
DAMAN AND DIU                     2     892     35
DELHI                          1399  106599  10080
GOA                              40    8963    428
GUJARAT                        1164  283123  12067
HARYANA                         582  147956   7231
HIMACHAL PRADESH                 26   21730    613
JAMMU AND KASHMIR                62   47434   1145
JHARKHAND                       170   74753   2357
KARNATAKA                       987  248728  10468
KERALA                          397   98110   5305
LADAKH                            0    1652     32
LAKSHADWEEP                       0     114      0
MADHYA PRADESH                  397  194520   6634
MAHARASHTRA                    2797  962520  25367
MANIPUR                           9   10051    175
MEGHALAYA                        11    1286     89
MIZORAM                           8    2002     52
NAGALAND                          2    1757     23
ODISHA                          281   87502   3798
PUDUCHERRY                       22    6702    266
PUNJAB                          337  141714   5021
RAJASTHAN                       616  328406   8952
SIKKIM                            8    1073     39
TAMIL NADU                     1050  431053  13954
TELANGANA                       713  150812   6783
TRIPURA                           9    3556    163
UTTAR PRADESH                   914  326045  11567
UTTARAKHAND                      79   39722   1237
WEST BENGAL                     772  111856   7657

In [ ]:
pivot_table_result.to_csv("state_wise_total.csv")

In [ ]:
print(df1.head())

       STATE_NAME Lg_Dist_Code  DISTRICT_NAME  MICRO  SMALL  MEDIUM  Total  \
0  ANDHRA PRADESH          502     ANANTHAPUR   7797    238      10   8045
1  ANDHRA PRADESH          503        CHITOOR   9623    351      19   9993
2  ANDHRA PRADESH          505  EAST GODAVARI  12347    615      49  13011
3  ANDHRA PRADESH          506         GUNTUR  11386    630      53  12069
4  ANDHRA PRADESH          510        KRISHNA  15189   1007      79  16275

  Last_Updated
0   2022-01-11
1   2022-01-11
2   2022-01-11
3   2022-01-11
4   2022-01-11

In [ ]:
print(df2.head())

       STATE_NAME Lg_Dist_Code  DISTRICT_NAME  MICRO  SMALL MEDIUM  Total  \
0  ANDHRA PRADESH          502     ANANTHAPUR  11370    483     33  11886
1  ANDHRA PRADESH          503        CHITOOR  13037    592     51  13680
2  ANDHRA PRADESH          505  EAST GODAVARI  16711   1044    123  17878
3  ANDHRA PRADESH          506         GUNTUR  15955   1678    169  17802
4  ANDHRA PRADESH          510        KRISHNA  20460   1673    165  22298

  Last_Updated
0   2022-01-11
1   2022-01-11
2   2022-01-11
3   2022-01-11
4   2022-01-11

Converting df2 "Lg_Dist_Code" column to same datatype as df1

In [ ]:
df2['Lg_Dist_Code'] = df2['Lg_Dist_Code'].astype(int)
common_columns = ['STATE_NAME', 'DISTRICT_NAME', 'Lg_Dist_Code', 'Last_Updated']

Merging both the DataFrame

In [ ]:
merged_df = pd.merge(df2, df1, on=["STATE_NAME", "DISTRICT_NAME", "Last_Updated", "Lg_Dist_Code"],how='inner', suffixes=('_x', '_y'))
print(merged_df.head())

       STATE_NAME Lg_Dist_Code  DISTRICT_NAME MICRO_x  SMALL_x MEDIUM_x  \
0  ANDHRA PRADESH          502     ANANTHAPUR   11370      483       33
1  ANDHRA PRADESH          503        CHITOOR   13037      592       51
2  ANDHRA PRADESH          505  EAST GODAVARI   16711     1044      123
3  ANDHRA PRADESH          506         GUNTUR   15955     1678      169
4  ANDHRA PRADESH          510        KRISHNA   20460     1673      165

  Total_x Last_Updated  MICRO_y  SMALL_y  MEDIUM_y  Total_y
0   11886   2022-01-11     7797      238        10     8045
1   13680   2022-01-11     9623      351        19     9993
2   17878   2022-01-11    12347      615        49    13011
3   17802   2022-01-11    11386      630        53    12069
4   22298   2022-01-11    15189     1007        79    16275

In [ ]:
merged_df['MEDIUM_x'] = pd.to_numeric(merged_df['MEDIUM_x'], errors='coerce')
merged_df['MICRO_x'] = pd.to_numeric(merged_df['MICRO_x'], errors='coerce')

pivot_table_result = merged_df.pivot_table(values=["MICRO_x", "SMALL_x", "MEDIUM_x", "MICRO_y", "SMALL_y", "MEDIUM_y"],
                                    index=['STATE_NAME'] ,
                                    aggfunc='sum',
                                           dropna=False)
pivot_table_result

,MEDIUM_x,MEDIUM_y,MICRO_x,MICRO_y,SMALL_x,SMALL_y
STATE_NAME,,,,,,
ANDAMAN AND NICOBAR ISLANDS,7,6,3905,2884,140,111
ANDHRA PRADESH,1030,422,153814,115320,10599,5799
ARUNACHAL PRADESH,11,6,2172,1201,99,53
ASSAM,309,200,65544,41051,3345,2182
BIHAR,413,245,247394,167835,5226,3908
CHANDIGARH,134,76,11435,9010,1007,687
CHHATTISGARH,566,257,74058,58905,4580,2726
DADAR AND NAGAR HAVELI,82,3,3730,2511,419,98
DAMAN AND DIU,56,2,1626,892,295,35
DELHI,2594,1399,166761,106599,19400,10080
GOA,91,40,11556,8963,713,428
GUJARAT,4168,1164,496564,283123,38098,12067
HARYANA,1696,582,213404,147956,16387,7231
HIMACHAL PRADESH,238,26,28509,21730,1559,613
JAMMU AND KASHMIR,148,62,73438,47434,1854,1145
JHARKHAND,308,170,97726,74753,3492,2357
KARNATAKA,2106,987,350026,248728,18996,10468
KERALA,785,397,147692,98110,8856,5305
LADAKH,0,0,2340,1652,49,32
LAKSHADWEEP,0,0,150,114,0,0
MADHYA PRADESH,1045,397,264197,194520,12190,6634
MAHARASHTRA,6377,2797,1305092,962520,49991,25367
MANIPUR,10,9,21076,10051,247,175
MEGHALAYA,21,11,1828,1286,147,89
MIZORAM,8,8,2942,2002,74,52
NAGALAND,4,2,2875,1757,53,23
ODISHA,463,281,116968,87502,5412,3798
PUDUCHERRY,52,22,9041,6637,486,260
PUNJAB,1269,337,212134,141714,12334,5021
RAJASTHAN,1672,616,501175,328406,19456,8952
SIKKIM,8,8,1382,1073,56,39
TAMIL NADU,2879,1050,668147,431053,30634,13954
TELANGANA,1649,713,199030,150812,12540,6783
TRIPURA,17,9,6103,3556,252,163
UTTAR PRADESH,2112,914,486415,326045,21530,11567
UTTARAKHAND,283,79,54666,39722,2618,1237
WEST BENGAL,1631,772,167593,111856,14088,7657